### ISSUE TITLE
sync fork from esm-wallaby and potentially the original esm repo

### ISSUE THREAD

**Issue by nktnet1** [httptoolkit/esm#1] opened 2024-08-26 12:50 UTC
Hi @pimterry,

Could you please merge the new changes from [esm-wallaby](https://github.com/wallabyjs/esm)?

Specifically these changes:
- https://github.com/httptoolkit/esm/compare/master...wallabyjs%3Aesm%3Amaster

Also, I think esm-wallaby is 3 commits behind the original (archived) [esm](https://github.com/standard-things/esm) repository - specifically these commits here
- https://github.com/wallabyjs/esm/compare/master...standard-things%3Aesm%3Amaster

Not sure if you'd like to integrate those changes in too.

---

On another note, I think pull request may be disabled for this repository - would you be able to enable it?
![image](https://github.com/user-attachments/assets/358a3005-f405-4cf1-8f07-e8951f10e568)

**Comment by pimterry** [comment] 2024-08-28 11:40
Hi @nktnet1, good suggestion, thanks. I've now updated `master` here to merge in those changes. Can you test that they work for you as expected? Once that's done I'll release them.

Regarding PRs, I have no idea what could be causing that, I've had a look through the settings but everything related to PRs seems enabled. https://github.com/orgs/community/discussions/61472 covers this but doesn't seem to have any clues either. Happy to enable anything if you can work out what the issue is. Alternatively it might just be something weird about the forking setup here, and it might work if you create a fork of this repo yourself, then set up the change and open the PR from there? Hard to know though.

**Comment by nktnet1** [comment] 2024-08-28 15:13
All good on the PR settings issue - no worries :). I think you're right about needing to fork this repo before making a PR back into it - I was trying to "sync fork" as a PR directly from GitHub interface which may have caused the issue.

Thanks a lot @pimterry! I'll have a go at testing on the weekends, although do you have any thoughts about also bringing the other changes from the original esm library (which esm-wallaby have yet to integrate)?

i.e. these 3 commits here:
- https://github.com/wallabyjs/esm/compare/master...standard-things:esm:master

![image](https://github.com/user-attachments/assets/900a034a-3e11-494c-9d5a-216b83303cb9)

**Comment by pimterry** [comment] 2024-09-02 14:40
@nktnet1 I've now cherry picked two of those commits too. I've skipped https://github.com/httptoolkit/esm/commit/cdd705344f6db482d2a958a55c97ba925fbfc088 as we already have https://github.com/httptoolkit/esm/commit/079e00f9a9bc0b61056c98eeb3342e5a3887bda3 from the other fork, which appears to do the same thing but go further. Let me know how your testing goes.

**Comment by nktnet1** [comment] 2024-09-07 13:41
@pimterry I tried it with Node 16 and it seemed to pass every test.

Ran into some problems building in node 20 and publishing in node 18 though (but this likely unrelated) - more details and logs here:
- https://github.com/httptoolkit/esm/issues/2#issuecomment-2335189430

**Comment by pimterry** [comment] 2024-09-09 07:45
I'll close this issue, since that upstream update is resolved and apparently working. We can discuss the rest on the other issue.

**Closed as completed by pimterry** 2024-09-09 07:45 UTC
